cloud:

# Loads default set of integrations. Do not remove.
default_config:

logbook:

# Text to speech
tts:
  - platform: google_translate

automation: !include_dir_merge_list automations/
ios: !include ios.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# You should update the version number at the end of the url
# after every update to avoid the old version being cached by Home Assistant
frontend:
  extra_module_url:
    - /hacsfiles/kiosk-mode/kiosk-mode.js?v6.4.0

panel_custom:
  - name: ha_integ
    sidebar_title: Integrations
    sidebar_icon: mdi:puzzle
    js_url: /api/hassio/app/entrypoint.js
    url_path: "config/integrations"
    embed_iframe: true
    require_admin: true
    config:
      ingress: core_configurator

  - name: ha_auto
    sidebar_title: Automations
    sidebar_icon: mdi:home-automation
    js_url: /api/hassio/app/entrypoint.js
    url_path: "config/automation"
    embed_iframe: true
    require_admin: true
    config:
      ingress: core_configurator

  - name: ha_addons
    sidebar_title: Add-ons
    sidebar_icon: mdi:puzzle-plus
    js_url: /api/hassio/app/entrypoint.js
    url_path: "hassio/dashboard"
    embed_iframe: true
    require_admin: true
    config:
      ingress: core_configurator

mqtt:

template: !include includes/template.yaml

climate: !include includes/climate.yaml

logger:
  default: info # Or your existing default log level
  logs:
    homeassistant.components.bluetooth: debug
    homeassistant.components.bluetooth_le_tracker: debug

zha_toolkit:

sensor: !include includes/sensors.yaml

# Shell commands for git operations
shell_command:
  git_push_config: /config/shell/git-push-config.sh
