- alias: Open Garage
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Open Garage
  action:
  - service: button.press
    entity_id: button.garage_open
  id: bff775fb07d6453faca8c1ae17d1de8c
- alias: Close Garage
  trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Close Garage
  action:
  - service: button.press
    entity_id: button.garage_close
  id: 4c9f79703221427ba33cbc5f0fc2eb13
- id: '1668582687707'
  alias: Garage Door - Notify After Open
  description: Will send notification if garage door is still open after 10 minutes.
  trigger:
  - platform: state
    entity_id:
    - cover.garage_door
    from: closed
    to: open
    for:
      hours: 0
      minutes: 10
      seconds: 0
  condition: []
  action:
  - service: script.garage_door_notification
    data: {}
  mode: single
- id: '1731171022698'
  alias: Garage Is Open Notification
  description: Sends notification when the garage door is opened.
  triggers:
  - type: opened
    device_id: 3c622461c8c971b8b3332b5ed7b93996
    entity_id: f39c322b59f9b934de12de865a7de3f5
    domain: binary_sensor
    trigger: device
  conditions: []
  actions:
  - action: notify.mobile_app_troys_iphone
    metadata: {}
    data:
      message: Garage Door is Open
      title: Garage Open
  mode: single
- id: '1731171259521'
  alias: Garage Is Closed Notification
  description: Sends notification when the garage door is opened.
  triggers:
  - type: not_opened
    device_id: 3c622461c8c971b8b3332b5ed7b93996
    entity_id: f39c322b59f9b934de12de865a7de3f5
    domain: binary_sensor
    trigger: device
  conditions: []
  actions:
  - action: notify.mobile_app_troys_iphone
    metadata: {}
    data:
      message: Garage Door is Closed
      title: Garage Open
  mode: single
